//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdmxStuff.GeneratedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ragdoll
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public int Person_Id { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
